@startuml [TITLE]

' skinparam linetype polyline
skinparam linetype ortho

!define AzurePuml https://raw.githubusercontent.com/travisnielsen/Azure-PlantUML/themesupport/dist
!includeurl AzurePuml/themes/dracula.puml

!includeurl AzurePuml/Analytics/AzureDatabricks.puml
!includeurl AzurePuml/Compute/AzureVirtualMachineScaleSet.puml
!includeurl AzurePuml/Management/AzureSubscription.puml
!includeurl AzurePuml/Networking/AzureFirewall.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Networking/AzureSubnet.puml
!includeurl AzurePuml/Networking/AzureExpressRoute.puml
!includeurl AzurePuml/Networking/AzureRouteTable.puml
!includeurl AzurePuml/Networking/AzureApplicationGateway.puml
!includeurl AzurePuml/Networking/AzureLoadBalancer.puml
!includeurl AzurePuml/Networking/AzureNAT.puml
!includeurl AzurePuml/Networking/AzureNSG.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Web/AzureAPIManagement.puml

' LAYOUT_LEFT_RIGHT

skinparam Rectangle {
	BorderColor<<peered>> ORANGE
	BorderThickness<<peered>> 8
    BackgroundColor<<container>> #000
    Color<<container>> #000
    FontColor<<container>> #000
}

skinparam rectangle<<e_stereo>> {
    BackgroundColor<<Region>> BACKGROUND
	BorderColor<<Region>> RED
    FontColor<<Region>> RED
	FontSize<<Region>> 32
	StereotypeFontSize<<Region>> 16
	StereotypeFontColor<<Region>> WHITE
	BackgroundColor<<AzureSubscription>> SELECTION
	BorderColor<<AzureSubscription>> CYAN
    BackgroundColor<<AzureVirtualNetwork>> BACKGROUND
    BorderColor<<AzureVirtualNetwork>> ORANGE
    BackgroundColor<<AzureSubnet>> SELECTION
    BorderColor<<AzureSubnet>> ORANGE
    BorderColor<<AzureRouteTable>> ORANGE
    BorderColor<<AzurePrivateLink>> ORANGE
	BorderColor<<AzureExpressRoute>> ORANGE
	BorderColor<<AzureVPNGateway>> ORANGE
    BorderColor<<AzureVirtualMachine>> PURPLE
    BorderColor<<AzureFunction>> PURPLE
    BorderColor<<AzureDataLakeStorage>> CYAN
    BorderColor<<AzureSqlDataWarehouse>> CYAN
    BorderColor<<AzureDataFactory>> CYAN
    BorderColor<<AzureFirewall>> RED
    BorderColor<<AzureNSG>> RED
    BorderColor<<AzureAPIManagement>> CYAN
    BorderColor<<AzureDatabricks>> PINK
}

skinparam BackgroundColor #000
skinparam ranksep 50
skinparam nodesep 50

[BODY]


@enduml